<a href="https://colab.research.google.com/github/Nirisha444/Worksheet/blob/main/WORKSHEET_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [57]:
import numpy as np

empty_array = np.empty((2, 2))
print(empty_array)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)


[[2.02018387e-315 0.00000000e+000]
 [1.96912990e-315 6.86751248e-322]]


In [ ]:
import numpy as np
ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
filled_array = np.full((3, 3), 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [15]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros_like(original_array)
print(zeros_array)


[[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])
ones_array = np.ones_like(original_array)
print(ones_array)


[[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)


[1 2 3 4]


Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
array = np.arange(10,50)
print (array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
import numpy as np
array = np.arange(9)
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.47209917621013486


In [11]:
import numpy as np
array = np.random.random((10,10))
min_value = array.min()
max_value = array.max()
print(min_value)
print(max_value)

0.0012353950430139538
0.992167247621237


In [16]:
import numpy as np
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
import numpy as np
array = np.array([1,2,0,0,4,0])
reversed_array = array[::-1]
print(reversed_array)

[0 4 0 0 2 1]


In [19]:
import numpy as np
array = np.ones((5,5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
import numpy as np
array = np.zeros((8,8))
array[1::2, 0::2] = 1
array[0::2, 1::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [22]:
import numpy as np
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
result = x+y
print(result)

[[ 6  8]
 [10 13]]


In [23]:
import numpy as np
x = np.array([[9,10],[11,12]])
result = x-y
print(result)

[[4 4]
 [4 4]]


In [24]:
import numpy as np
x = np.array([[1,2], [3,5]])
result = x * 3
print(result)

[[ 3  6]
 [ 9 15]]


In [27]:
import numpy as np
x = np.array([[1,2], [3,5]])
result = np.square(x)
print(result)

[[ 1  4]
 [ 9 25]]


In [31]:
import numpy as np
x = np.array([[1, 2],
              [3, 5]])

y = np.array([[5, 6],
              [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

result_vw = np.dot(v, w)
print("Dot product of v and w:", result_vw)

result_xv = np.dot(x, v)
print("Dot product of x and v:", result_xv)

result_xy = np.dot(x, y)
print("Dot product of x and y:")
print(result_xy)

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]


In [32]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

concat_xy_row = np.vstack((x, y))
print("Concatenate x and y along rows:\n", concat_xy_row)

concat_vw_col = np.hstack((v, w))
print("Concatenate v and w along columns:\n", concat_vw_col)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [ 9 10 11 12]


In [58]:
import numpy as np

x = np.array([[1,2],[3,5]])
v = np.array([9,10])

try:
    concat_xv = np.concatenate((x, v))
    print("Concatenation successful:\n", concat_xv)
except ValueError as e:
    print("Error concatenating x and v:", e)


Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


The error occurs because 'x' is a 2-dimensional array (shape (2, 2)) and 'v' is a 1-dimensional array (shape (2,)). NumPy's concatenate function requires that all arrays being concatenated have the same number of dimensions. You cannot directly concatenate arrays of different dimensions without reshaping one of them to match the other's dimensions, or using functions specifically designed for combining arrays of different dimensions (e.g., broadcasting or adding a new axis).")

Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function

In [51]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
A1 = np.linalg.inv(A)
I = A.dot(A1)
I = np.round(I)
print("A*A^-1=I:\n",I)

A*A^-1=I:
 [[1. 0.]
 [0. 1.]]


In [52]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
AB = A.dot(B)
BA = B.dot(A)
print("AB:\n",AB)
print("BA:\n",BA)
print("AB != BA")

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA


In [53]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
left_side = AB.T
right_side = B.T.dot(A.T)
print(("(AB)^T:\n"),left_side)
print("B^T A^T:\n",right_side)
print("(AB)^T = B^T A^T")

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T = B^T A^T


In [56]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(A), B)
print(X)

[ 2.  1. -2.]
